import React, { useState } from "react";
import { useTheme } from "@mui/material/styles";
import { FormControl, MenuItem, OutlinedInput, Select } from "@mui/material";
import { useSelector } from "react-redux";

const ITEM_HEIGHT = 48;
const ITEM_PADDING_TOP = 8;
const MenuProps = {
  PaperProps: {
    style: {
      maxHeight: ITEM_HEIGHT * 4.5 + ITEM_PADDING_TOP,
      width: 180,
    },
  },
};

const carTypes = [
  "ILX",
  "MDX",
  "MDX Sport Hybrid",
  "NSX",
  "RDX",
  "RLX",
  "RLX Sport Hybrid",
  "TLX",
  "4C Spider",
  "Giulia",
  "Stelvio",
  "A3",
  "A4",
  "A5",
  "A6",
  "A6 allroad",
  "A7",
  "Q3",
  "Q5",
  "Q7",
  "Q8",
  "R8",
  "S4",
  "S8",
  "SQ5",
  "TT",
  "2 Series",
  "3 Series",
  "4 Series",
  "5 Series",
  "7 Series",
  "8 Series",
  "M2",
  "X1",
  "X2",
  "X3",
  "X3 M",
  "X4",
  "X5",
  "X6",
  "X7",
  "Z4",
  "Enclave",
  "Encore",
  "Encore GX",
  "Envision",
  "Regal Sportback",
  "Regal TourX",
  "CT4",
  "CT5",
  "CT6",
  "CT6-V",
  "Escalade",
  "Escalade ESV",
  "XT4",
  "XT5",
  "XT6",
  "Blazer",
  "Bolt EV",
  "Camaro",
  "Colorado Crew Cab",
  "Colorado Extended Cab",
  "Corvette",
  "Equinox",
  "Express 2500 Cargo",
  "Express 3500 Cargo",
  "Impala",
  "Malibu",
  "Silverado 1500 Crew Cab",
  "Silverado 1500 Double Cab",
  "Silverado 1500 Regular Cab",
  "Silverado 2500 HD Crew Cab",
  "Silverado 2500 HD Double Cab",
  "Silverado 3500 HD Crew Cab",
  "Sonic",
  "Spark",
  "Suburban",
  "Tahoe",
  "Traverse",
  "Trax",
  "300",
  "Pacifica",
  "Pacifica Hybrid",
  "Voyager",
  "Challenger",
  "Charger",
  "Durango",
  "Grand Caravan Passenger",
  "Journey",
  "124 Spider",
  "500L",
  "500X",
  "EcoSport",
  "Edge",
  "Escape",
  "Expedition",
  "Expedition MAX",
  "Explorer",
  "F150 Regular Cab",
  "F150 Super Cab",
  "F150 SuperCrew Cab",
  "F250 Super Duty Crew Cab",
  "F250 Super Duty Regular Cab",
  "F250 Super Duty Super Cab",
  "F350 Super Duty Crew Cab",
  "F350 Super Duty Super Cab",
  "F450 Super Duty Crew Cab",
  "Fusion",
  "Fusion Plug-in Hybrid",
  "Mustang",
  "Ranger SuperCab",
  "Ranger SuperCrew",
  "Transit 250 Cargo Van",
  "Transit 350 Passenger Van",
  "Transit Connect Cargo Van",
  "Transit Connect Passenger Wagon",
  "Sprinter 1500 Cargo",
  "Sprinter 1500 Passenger",
  "Sprinter 2500 Cargo",
  "Sprinter 2500 Crew",
  "Sprinter 2500 Passenger",
  "Sprinter 3500 Cargo",
  "Sprinter 3500 Crew",
  "Sprinter 3500 XD Crew",
  "Sprinter 3500XD Cargo",
  "Sprinter 4500 Cargo",
  "Sprinter 4500 Crew",
  "G70",
  "G80",
  "G90",
  "Acadia",
  "Canyon Crew Cab",
  "Sierra 1500 Crew Cab",
  "Sierra 1500 Double Cab",
  "Sierra 1500 Regular Cab",
  "Sierra 2500 HD Crew Cab",
  "Sierra 3500 HD Crew Cab",
  "Terrain",
  "Yukon",
  "Yukon XL",
  "Accord",
  "Accord Hybrid",
  "Civic",
  "Civic Type R",
  "Clarity Fuel Cell",
  "Clarity Plug-in Hybrid",
  "CR-V",
  "CR-V Hybrid",
  "Fit",
  "HR-V",
  "Insight",
  "Odyssey",
  "Passport",
  "Pilot",
  "Ridgeline",
  "Accent",
  "Elantra",
  "Elantra GT",
  "Ioniq Electric",
  "Ioniq Hybrid",
  "Ioniq Plug-in Hybrid",
  "Kona",
  "Kona Electric",
  "NEXO",
  "Palisade",
  "Santa Fe",
  "Sonata",
  "Sonata Hybrid",
  "Tucson",
  "Veloster",
  "Venue",
  "Q50",
  "Q60",
  "QX50",
  "QX60",
  "QX80",
  "E-PACE",
  "F-PACE",
  "F-TYPE",
  "I-PACE",
  "XE",
  "XF",
  "Cherokee",
  "Compass",
  "Gladiator",
  "Grand Cherokee",
  "Renegade",
  "Wrangler",
  "Wrangler Unlimited",
  "Cadenza",
  "Forte",
  "K900",
  "Niro",
  "Niro EV",
  "Niro Plug-in Hybrid",
  "Optima",
  "Optima Hybrid",
  "Optima Plug-in Hybrid",
  "Rio",
  "Sedona",
  "Sorento",
  "Soul",
  "Sportage",
  "Stinger",
  "Telluride",
  "Defender 110",
  "Defender 90",
  "Discovery",
  "Discovery Sport",
  "Range Rover",
  "Range Rover Evoque",
  "Range Rover Sport",
  "Range Rover Velar",
  "ES",
  "GS",
  "GX",
  "IS",
  "LC",
  "LS",
  "LX",
  "NX",
  "RC",
  "RX",
  "UX",
  "Aviator",
  "Continental",
  "Corsair",
  "MKZ",
  "Nautilus",
  "Navigator",
  "Navigator L",
  "CX-3",
  "CX-30",
  "CX-5",
  "CX-9",
  "MAZDA3",
  "MAZDA6",
  "MX-5 Miata",
  "MX-5 Miata RF",
  "A-Class",
  "C-Class",
  "CLA",
  "CLS",
  "E-Class",
  "G-Class",
  "GLA",
  "GLB",
  "GLC",
  "GLE",
  "GLS",
  "Mercedes-AMG A-Class",
  "Mercedes-AMG C-Class",
  "Mercedes-AMG CLS",
  "Mercedes-AMG GLC",
  "Mercedes-AMG GLC Coupe",
  "Metris WORKER Cargo",
  "Metris WORKER Passenger",
  "S-Class",
  "SLC",
  "Sprinter 1500 Cargo",
  "Sprinter 1500 Passenger",
  "Sprinter 2500 Cargo",
  "Sprinter 2500 Crew",
  "Sprinter 2500 Passenger",
  "Sprinter 3500 Cargo",
  "Sprinter 3500 Crew",
  "Sprinter 3500 XD Cargo",
  "Sprinter 3500 XD Crew",
  "Sprinter 4500 Cargo",
  "Sprinter 4500 Crew",
  "Clubman",
  "Countryman",
  "Hardtop 2 Door",
  "Hardtop 4 Door",
  "Eclipse Cross",
  "Mirage",
  "Mirage G4",
  "Outlander",
  "Outlander PHEV",
  "Outlander Sport",
  "370Z",
  "Altima",
  "Armada",
  "Frontier Crew Cab",
  "Frontier King Cab",
  "GT-R",
  "Kicks",
  "LEAF",
  "Maxima",
  "Murano",
  "NV1500 Cargo",
  "NV200",
  "NV2500 HD Cargo",
  "NV3500 HD Cargo",
  "NV3500 HD Passenger",
  "Pathfinder",
  "Rogue",
  "Rogue Sport",
  "Sentra",
  "Titan Crew Cab",
  "Titan King Cab",
  "TITAN XD Crew Cab",
  "Versa",
  "718 Boxster",
  "718 Cayman",
  "718 Spyder",
  "911",
  "Cayenne",
  "Cayenne Coe",
  "Macan",
  "Panamera",
  "Taycan",
  "1500 Classic Crew Cab",
  "1500 Classic Quad Cab",
  "1500 Crew Cab",
  "1500 Quad Cab",
  "2500 Crew Cab",
  "3500 Crew Cab",
  "ProMaster Cargo Van",
  "ProMaster City",
  "Ascent",
  "BRZ",
  "Crosstrek",
  "Forester",
  "Impreza",
  "Legacy",
  "Outback",
  "WRX",
  "Model 3",
  "Model S",
  "Model X",
  "Model Y",
  "4Runner",
  "86",
  "Avalon",
  "Avalon Hybrid",
  "Camry",
  "Camry Hybrid",
  "C-HR",
  "Corolla",
  "Corolla Hatchback",
  "Corolla Hybrid",
  "GR Supra",
  "Highlander",
  "Highlander Hybrid",
  "Land Cruiser",
  "Mirai",
  "Prius",
  "Prius Prime",
  "RAV4",
  "RAV4 Hybrid",
  "Sequoia",
  "Sienna",
  "Tacoma Access Cab",
  "Tacoma Double Cab",
  "Tundra CrewMax",
  "Tundra Double Cab",
  "Yaris",
  "Yaris Hatchback",
  "Arteon",
  "Atlas",
  "Atlas Cross Sport",
  "Golf",
  "Golf GTI",
  "Jetta",
  "Jetta GLI",
  "Passat",
  "Tiguan",
  "S60",
  "S90",
  "V60",
  "V90",
  "XC40",
  "XC60",
];

function getStyles(name, carTypes, theme) {
  return {
    fontWeight:
      carTypes.indexOf(name) === -1
        ? theme.typography.fontWeightRegular
        : theme.typography.fontWeightMedium,
  };
}

const ModelsSelection = (props) => {
  const { name, onTypeChange } = props;
  const theme = useTheme();
  const data = useSelector((state) => state.basic.data);

  const handleChange = (event) => {
    const {
      target: { value },
    } = event;
    onTypeChange(typeof value === "string" ? value.split(",") : value);
  };

  return (
    <>
      <FormControl>
        <Select
          displayEmpty
          value={data.model}
          onChange={handleChange}
          input={<OutlinedInput size="small" />}
          renderValue={(selected) => {
            if (!selected) {
              return <em>Type</em>;
            }
            return selected;
          }}
          MenuProps={MenuProps}
          inputProps={{ "aria-label": "Without label" }}
        >
          <MenuItem disabled value="">
            <em>--Type--</em>
          </MenuItem>
          {carTypes.map((name) => (
            <MenuItem
              key={name}
              value={name}
              style={getStyles(name, carTypes, theme)}
            >
              {name}
            </MenuItem>
          ))}
        </Select>
      </FormControl>
    </>
  );
};

export default ModelsSelection;
